### ISSUE TITLE
Connection issue with ethstats server. Not able to register node

### ISSUE THREAD

**Issue by adilimroz** [Alethio/ethstats-cli#19]
I am trying to register a node to a different server http://mon15.ethdevops.io/ . I have ethstats-cli installed with all the dependencies and the ethereum node with parity running on port 8545.

But the connection to ethstats server seem to drop frequently and so not able to do anything with it.

Please look at the screenshot.

![Screenshot from 2019-09-26 13-55-52](https://user-images.githubusercontent.com/5220489/65672099-19769a80-e066-11e9-9631-6aa34502c7b2.png)

**Comment by baxy** [comment]
Hello,

From what I see, you provided the --secret flag, that's valid only for the old ethstats client. I think you are trying to connect ethstats-cli to an old ethstats server. There are breaking changes in the communication protocol for the new version at server level. If you want to use the new version you'll need to install also the new server. The simplest way to install the new server is via docker compose. Here are some examples: https://github.com/Alethio/ethstats-network-server/tree/master/docker/lite-mode. There is also this article with more details, check ethstats section: https://medium.com/alethio/a-guide-to-deploying-alethios-free-open-source-products-18216617722e

Hope it helps
