### ISSUE TITLE
goerli.ethstats.io is stuck at block 2,079,271

### ISSUE THREAD

**Issue by mkmpro** [Alethio/ethstats-cli#22]
#### Describe the bug
goerli.ethstats.io doesn't show the actual state of the chain.

#### To Reproduce
Open https://goerli.ethstats.io/ in the browser
Look at last block, which is > 3179574s ago 

#### Expected behavior
Last block should be less then 60 seconds ago

**Comment by baxy** [comment]
Hi,

Thanks for the feedback, the issues was fixed.
